### ISSUE TITLE
background of pages

### ISSUE THREAD

**Issue by ISPA-DRC** [Rivkanexus/ISPA-DRC#11]
The preference is to have an off-white background

**Comment by Nicotshintu** [comment]
> > The preference is to have an off-white background
> 
> Please be specific and give an example colour. I will need the HEX code such as #F5F5F5. You can pick a colour from here: https://htmlcolorcodes.com/

We rely on your expertise for the choice of background colors for each web page.

**Comment by Rivkanexus** [comment]
Nico - I would advise leaving the background colour as it is. This is becaus ethroughout the site, there are already some sections in grey or other colours. Changing the background colopur site-wide means we will need to change these also to fit. Let me know if you agree.

**Comment by Nicotshintu** [comment]
Hi Rebecca, 

I hope you are well.

Your proposals are welcom. I agree. 

Best Regards 

Nico TSHINTU 

10 juin 2024 22:17 "Rivkanexus" ***@***.*** ***@***.******@***.***>)> a écrit:
	Nico - I would advise leaving the background colour as it is. This is becaus ethroughout the site, there are already some sections in grey or other colours. Changing the background colopur site-wide means we will need to change these also to fit. Let me know if you agree.
