### ISSUE TITLE
menu "Statistiques"

### ISSUE THREAD

**Issue by ISPA-DRC** [Rivkanexus/ISPA-DRC#7]
_Please add the menu "Statistiques" _before the menu_ "Contact"

**Comment by ISPA-DRC** [comment]
in statistics add the following subheadings: RDC-IX stat, KINIX sast, LUBIX stat, GOMIX stat.

**Comment by Nicotshintu** [comment]
for statistics links, it would be preferable to provide the links in this way:

Total RDC-IX traffic: click here.. ( national all traffic)
Trafix KINIX: click here...
LUBIX traffic: click here...
GOMIX traffic: click here..

so, when the IXP Manager configuration is finished, there will be a need to do the redirection.

**Comment by Rivkanexus** [comment]
I have implemented the total traffic graph - day, week, month and year for now, as the graphs for GOMIX and LUBIX are not working on its own.
