### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ISPA-DRC** [Rivkanexus/ISPA-DRC#8]
The ISPA-DRC members logo ISPA-DRC membres list : 
[SITE WEB DES OPERATEURS .docx](https://github.com/Rivkanexus/ISPA-DRC/files/14873860/SITE.WEB.DES.OPERATEURS.docx)
 
![Logo_airtel](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/ff87fc65-b01b-4457-89cb-fdb2f12c3c4e)
![Logo_orange](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/126677c4-87ac-4a9b-bb7f-7b825ddad5bc)
![logo_VODACOM](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/e9ab4db1-0910-47b5-909f-74d25cafb25d)
![Logo_Fastcongo](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/bf7fc6f0-730b-4ba9-aed9-09d3c6561959)
![logo_GVA](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/feabbd36-bce3-48f2-8d22-f4198d992ac1)
![Logo_GBS](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/f6e5f9f6-7c4b-4e4e-baff-cebc5509bfa9)
![logo_bcs](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/1a2816e7-8c89-4161-8349-1e5314711118)
![Logo_ORION](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/e1b7333a-6337-41b1-a917-f2a55b45e34d)
![logo_standard](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/d4887ee3-0c96-41e3-ac0b-682d4d16603f)
![logo_Africell](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/f2c11239-e964-47b4-b270-3b3647f5d716)
![Logo_KIWI](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/80e93ae5-5031-4ca2-bed5-7367002caad9)
![Logo_Techplus](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/00662f1b-cff4-4710-8e0b-9ca624fb9abd)
![Logo_dhi](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/43e93a4a-9a2f-4d81-97f0-9e680d52b303)
![Logo_csquared](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/edba5ae4-e546-4283-ac0f-ce31e3d1d77f)
![logo_comtech](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/7379534d-bb35-45ab-a7b0-0eb3f5f677eb)
![Logo_fastnet](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/1282d96f-6c56-46a9-86fd-e4872c91bc78)
![Logo_United](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/8ddaa60c-b722-4223-89c7-df80186d770f)
![Logo_micrcom](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/58da72ec-32ad-4f43-8e38-851d4eac47f9)
![Logo_Afrinet](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/0765e465-6a91-484d-8c7c-93c5ce290497)
![logo_LIQUID](https://github.com/Rivkanexus/ISPA-DRC/assets/165366542/3273affd-e2cb-4525-998e-7170ed1da08c)

**Comment by Rivkanexus** [comment]
The logo of uni-limited is missing. I found it on the web, but you need to confirm if it's correct.
